### ISSUE TITLE
It's me again :)

### ISSUE THREAD

**Issue by Cyperfr3ak** [pqqqqq/DirectScript#2]
Sorry it's me again ^^
But could you please release the jar too ? can't get the project to compile. Never programmed with Sponge just with forge and Pixelmon.

**Comment by pqqqqq** [comment]
I have already released a new version containing this fix, version 2.0.1-SNAPSHOT.
https://github.com/pqqqqq/DirectScript/releases/tag/2.0.1-SNAPSHOT

**Comment by Cyperfr3ak** [comment]
But there's no jar file just the sources

**Comment by pqqqqq** [comment]
I've updated the same link with the jar file, sorry about that.
Enjoy!
